/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;
import sun.reflect.generics.tree.Tree;

/**
 *
 * @author Usuario
 */
public class SistemaView extends javax.swing.JFrame {

    int i=6;
    String name;
    DefaultTreeModel arbol;
    
    /**
     * Creates new form SistemaView
     */
    public SistemaView() {
        initComponents();
        
        
        
        DefaultMutableTreeNode raiz = new DefaultMutableTreeNode("raiz");
        DefaultMutableTreeNode nodo1 = new DefaultMutableTreeNode("nodo1");
        DefaultMutableTreeNode nodo2 = new DefaultMutableTreeNode("nodo2");
        DefaultMutableTreeNode nodo3 = new DefaultMutableTreeNode("nodo3");
        DefaultMutableTreeNode nodo4 = new DefaultMutableTreeNode("nodo4");
        DefaultMutableTreeNode nodo5 = new DefaultMutableTreeNode("nodo5");
        DefaultMutableTreeNode nodo6 = new DefaultMutableTreeNode("nodo6");
        nodo2.add(nodo3);
        nodo1.add(nodo2);
        nodo5.add(nodo6);
        nodo4.add(nodo5);
        raiz.add(nodo1);
        raiz.add(nodo4);
        arbol = new DefaultTreeModel(raiz);
        
        
        this.demoarbol.setModel(arbol);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        demoarbol = new javax.swing.JTree();
        jButton1 = new javax.swing.JButton();
        txtnodo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        demoarbol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                demoarbolMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(demoarbol);

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtnodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtnodoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtnodo, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(120, 120, 120))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txtnodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtnodoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnodoMouseClicked

    private void demoarbolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_demoarbolMouseClicked
              
       DefaultMutableTreeNode parentNode ;
       TreePath parentPath = demoarbol.getSelectionPath();
       parentNode = (DefaultMutableTreeNode) (parentPath.getLastPathComponent());
       
       txtnodo.setText(parentNode.getChildCount()+" "+parentNode.getLevel());
       
       
    }//GEN-LAST:event_demoarbolMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       agregarNodo();
            
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree demoarbol;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtnodo;
    // End of variables declaration//GEN-END:variables

 public void agregarNodo(){
     
     TreePath parentPath = demoarbol.getSelectionPath();
    if (parentPath != null) {
        
        
        name = "nodo"+i;
     String cadena = JOptionPane.showInputDialog(this,"ingrese el nombre");
     DefaultMutableTreeNode name = new DefaultMutableTreeNode(cadena);
     
     DefaultMutableTreeNode parentNode = null;
   

    
        parentNode = (DefaultMutableTreeNode) (parentPath.getLastPathComponent());
        DefaultMutableTreeNode child = new DefaultMutableTreeNode(cadena);
        arbol.insertNodeInto(child, parentNode, parentNode.getChildCount());
        this.demoarbol.setModel(arbol);
        } else {
        JOptionPane.showMessageDialog(this, "seleccione un nodo");
    }
        
 }


}
